version: '3.8'

services:
  app:
    build: .
    command: npm run dev
    ports:
      - 3000:3000
    environment:
      - PG_PASSWORD=password
      - PG_DB=cadDoBem
      - PG_USER=postgres
      - PG_HOST=db
      - SECRET=ultrasecret
    volumes:
      - .:/code

  db:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cadDoBem
    ports:
      - 5432:5432